// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcdmcrpikadgrdujasnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZG1jcnBpa2FkZ3JkdWphc250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTgyMDIsImV4cCI6MjA2Mzc3NDIwMn0.jpkhV9KbFkXazy3mwqV3JKKxRkB7WnmH_j7CgEkrJZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);